### ISSUE TITLE
TODO: describe full algorithm for players' learning

### ISSUE THREAD

**Issue by ikuzart** [artoorio/game1#6]
[REDACTED]

**Comment by ikuzart** [comment]
```
class Game:
    STONES_FOR_WIN = 24

    def __init__(self, players: list):
        self.stones_on_table = random.randint(1, 23)
        self.players = players

    def _update_state(self):
        pass

    def play(self):
        win = False
        while not win:
            for player in self.players:
                self.stones_on_table = player.make_step(self.stones_on_table, self.STONES_FOR_WIN)
                if self.stones_on_table >= self.STONES_FOR_WIN:
                    win = True
                    break

    def give_rewards(self):
        pass
```

**Comment by ikuzart** [comment]
вот по условию у нас начальное состояние рандомное от 1 до 23, условия выйграша константа

наш агент, Player должен получать состояние окружения и выбирать действие на основе вознаграждения

у игры должно быть состояние, это не только кол-во камней, но и ходы другого игрока, мы должны обновлять состояние после каждого хода

**Comment by artoorio** [comment]
да, ты прав, моя версия - это скорее "выбор хода на основе истории игр", я еще не изучил вопрос оценки состояния. в данном случае цель была научить играть, не разрабатывая алгоритм логики хода, не продумывая никакой тактики. Если запустить 100 партий с выводом ходов каждого игрока - то становится видно как проигрывающий меняет свой выбор

**Comment by artoorio** [comment]
выбор игрока будет такой - если на столе 11 камней, то положить еще один камень или удвоить (12 vs 22), через н-ное количество партий он поймет, что оставлять 12 камней после себя - это путь к проигрышу
